### ISSUE TITLE
Write a description

### ISSUE THREAD

**Issue by razzeee** [nicokimmel/genkiarcade-electron#1]
Curently the description https://github.com/nicokimmel/shadowcast-electron/blob/main/flatpak/de.nicokimmel.shadowcast-electron.metainfo.xml#L16 seems to mirror the summary, which is not a good thing. Ideally it should give more insight.

You can find some more infos here https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#description

**Comment by nicokimmel** [comment]
Addressed in [#eb6e0ec76d40e1626ef8770804831937d339eadd](https://github.com/nicokimmel/shadowcast-electron/commit/eb6e0ec76d40e1626ef8770804831937d339eadd), will be included in next update.

**Comment by razzeee** [comment]
FYI, you might want to redo the screenshots in non german, as the flathub website otherwise won't show anything.

**Comment by nicokimmel** [comment]
Mhh, did not think about that one. I might just remove the german flag because there is not much sense in setting my switch to english just for 2 screenshots that almost look the same. Thank you!
